name: Bug Report
description: Create a bug report

body:
  - type: markdown
    attributes:
      value: |
        What not to report:

        - Errors in anything other than the org's device tree
        - Missing Builds
        - Feature requests

        Be sure to mention that you are using additional mods when reporting a problem (for example: Magisk)

        If you need help, contact me on Telegram at https://t.me/Vhmit

  - type: input
    attributes:
      label: Build Date
      description: |
        Anything that can help us identify the build you are using  
        Example: `lineage-18.1-20240222-UNOFFICIAL-deen`
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Device
      multiple: false
      options:
        - Select one
        - deen
        - jeter
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Version
      multiple: false
      options:
        - Select one
        - Q (10)
        - R (11)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior. Screenshots can be provided in the issue body below.
        If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)
        and double check that the rendered preview is not broken.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible Solution
      description: Not obligatory, but suggest a fix/reason for the bug.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before posting the issue, go through the steps you've written down to make sure
        the steps provided are detailed and clear.
